name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        # Same version as used by the AWS Lambda in MyCloud
        node-version: 14.17.3
    - name: Installing dependencies
      run: |
        npm -v
        npm i
    - name: Running unit tests
      run: npm run test
